FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json .
RUN npm install
COPY . .
RUN npm run build
RUN npm install --omit=dev

#Production stage
FROM gcr.io/distroless/nodejs20-debian12 AS production

WORKDIR /app

COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
CMD ["dist/main.js"]